#
# StatTrackers
# by Auxilor
#

gui:
  rows: 1
  title: "Stats"

discover-recipes: true
display-at-top: false # If the stattrackers should be displayed at the top of lore rather than at the bottom

stat:
  damage_dealt:
    display: "&bDamage Dealt: %value%"
    applicable-to:
      - sword
      - bow
      - trident
      - axe
    tracker:
      item: compass
      name: "&eTracker - Damage Dealt"
      lore:
        - "&8Drop this onto an item with /stattrackers"
        - "&8to display the amount of damage dealt"
      craftable: true
      recipe:
        - iron_sword
        - iron_sword
        - iron_sword

        - iron_sword
        - compass
        - iron_sword

        - iron_sword
        - iron_sword
        - iron_sword

  criticals_dealt:
    display: "&bCriticals Dealt: %value%"
    applicable-to:
      - sword
      - axe
    tracker:
      item: compass
      name: "&eTracker - Criticals Dealt"
      lore:
        - "&8Drop this onto an item with /stattrackers"
        - "&8to display the amount of criticals dealt"
      craftable: true
      recipe:
        - iron_sword
        - obsidian
        - iron_sword

        - obsidian
        - compass
        - obsidian

        - iron_sword
        - obsidian
        - iron_sword

  arrows_shot:
    display: "&bArrows Shot: %value%"
    applicable-to:
      - bow
    tracker:
      item: compass
      name: "&eTracker - Arrows Shot"
      lore:
        - "&8Drop this onto an item with /stattrackers"
        - "&8to display the amount of arrows shot"
      craftable: true
      recipe:
        - air
        - arrow
        - air

        - arrow
        - compass
        - arrow

        - air
        - arrow
        - air

  blocks_broken:
    display: "&bBlocks Broken: %value%"
    applicable-to:
      - pickaxe
      - axe
      - shovel
      - hoe
      - shears
    tracker:
      item: compass
      name: "&eTracker - Blocks Broken"
      lore:
        - "&8Drop this onto an item with /stattrackers"
        - "&8to display the amount of blocks broken"
      craftable: true
      recipe:
        - iron_pickaxe
        - iron_pickaxe
        - iron_pickaxe

        - iron_pickaxe
        - compass
        - iron_pickaxe

        - iron_pickaxe
        - iron_pickaxe
        - iron_pickaxe

  damage_blocked:
    display: "&bDamage Blocked: %value%"
    applicable-to:
      - shield
    tracker:
      item: compass
      name: "&eTracker - Damage Blocked"
      lore:
        - "&8Drop this onto an item with /stattrackers"
        - "&8to display the amount of damage blocked"
      craftable: true
      recipe:
        - air
        - shield
        - air

        - shield
        - compass
        - shield

        - air
        - shield
        - air

  damage_taken:
    display: "&bDamage Taken While Wearing: %value%"
    applicable-to:
      - helmet
      - chestplate
      - leggings
      - boots
      - elytra
    tracker:
      item: compass
      name: "&eTracker - Damage Taken While Wearing"
      lore:
        - "&8Drop this onto an item with /stattrackers"
        - "&8to display the amount of damage taken while wearing"
      craftable: true
      recipe:
        - air
        - iron_helmet
        - air

        - iron_chestplate
        - compass
        - iron_leggings

        - air
        - iron_boots
        - air

  distance_flown:
    display: "&bDistance Flown: %value%"
    applicable-to:
      - elytra
    tracker:
      item: compass
      name: "&eTracker - Distance Flown"
      lore:
        - "&8Drop this onto an item with /stattrackers"
        - "&8to display the distance flown"
      craftable: true
      recipe:
        - air
        - phantom_membrane
        - air

        - phantom_membrane
        - compass
        - phantom_membrane

        - air
        - phantom_membrane
        - air

  distance_sneaked:
    display: "&bDistance Sneaked: %value%"
    applicable-to:
      - boots
    tracker:
      item: compass
      name: "&eTracker - Distance Sneaked"
      lore:
        - "&8Drop this onto an item with /stattrackers"
        - "&8to display the distance travelled while sneaking"
      craftable: true
      recipe:
        - air
        - leather_boots
        - air

        - leather_boots
        - compass
        - leather_boots

        - air
        - leather_boots
        - air

  distance_jumped:
    display: "&bDistance Jumped: %value%"
    applicable-to:
      - boots
    tracker:
      item: compass
      name: "&eTracker - Distance Jumped"
      lore:
        - "&8Drop this onto an item with /stattrackers"
        - "&8to display the distance jumped"
      craftable: true
      recipe:
        - slime_ball
        - leather_boots
        - slime_ball

        - leather_boots
        - compass
        - leather_boots

        - slime_ball
        - leather_boots
        - slime_ball

  distance_sprinted:
    display: "&bDistance Sprinted: %value%"
    applicable-to:
      - boots
    tracker:
      item: compass
      name: "&eTracker - Distance Sprinted"
      lore:
        - "&8Drop this onto an item with /stattrackers"
        - "&8to display the distance sprinted"
      craftable: true
      recipe:
        - air
        - golden_boots
        - air

        - golden_boots
        - compass
        - golden_boots

        - air
        - golden_boots
        - air

  item_damage:
    display: "&bTotal Item Damage: %value%"
    applicable-to:
      - all
    tracker:
      item: compass
      name: "&eTracker - Total Item Damage"
      lore:
        - "&8Drop this onto an item with /stattrackers"
        - "&8to display the amount of durability damage"
        - "&8any item has taken"
      craftable: true
      recipe:
        - air
        - air
        - air

        - anvil
        - compass
        - anvil

        - air
        - air
        - air

  mobs_killed:
    display: "&bMobs Killed: %value%"
    applicable-to:
      - sword
      - bow
      - trident
      - axe
    tracker:
      item: compass
      name: "&eTracker - Mobs Killed"
      lore:
        - "&8Drop this onto an item with /stattrackers"
        - "&8to display the amount of mobs killed"
      craftable: true
      recipe:
        - air
        - rotten_flesh
        - air

        - bone
        - compass
        - string

        - air
        - gunpowder
        - air

  players_killed:
    display: "&bPlayers Killed: %value%"
    applicable-to:
      - sword
      - bow
      - trident
      - axe
    tracker:
      item: compass
      name: "&eTracker - Players Killed"
      lore:
        - "&8Drop this onto an item with /stattrackers"
        - "&8to display the amount of players killed"
      craftable: true
      recipe:
        - diamond_sword
        - diamond_sword
        - diamond_sword

        - diamond_sword
        - compass
        - diamond_sword

        - diamond_sword
        - diamond_sword
        - diamond_sword

  times_jumped:
    display: "&bTimes Jumped: %value%"
    applicable-to:
      - boots
    tracker:
      item: compass
      name: "&eTracker - Times Jumped"
      lore:
        - "&8Drop this onto an item with /stattrackers"
        - "&8to display the amount of times you've jumped"
      craftable: true
      recipe:
        - air
        - slime_ball
        - air

        - slime_ball
        - compass
        - slime_ball

        - air
        - slime_ball
        - air

  experience_absorbed:
    display: "&bExperience Absorbed: %value%"
    applicable-to:
      - helmet
      - chestplate
      - leggings
      - boots
      - elytra
    tracker:
      item: compass
      name: "&eTracker - Experience Absorbed"
      lore:
        - "&8Drop this onto an item with /stattrackers"
        - "&8to display the amount experience you've absorbed"
        - "&8while wearing a piece of armor"
      craftable: true
      recipe:
        - air
        - emerald
        - air

        - emerald
        - compass
        - emerald

        - air
        - emerald
        - air

  bosses_killed:
    display: "&bBosses Killed: %value%"
    applicable-to:
      - sword
      - bow
      - trident
      - axe
    tracker:
      item: compass
      name: "&eTracker - Bosses Killed"
      lore:
        - "&8Drop this onto an item with /stattrackers"
        - "&8to display the amount of bosses killed"
      craftable: true
      recipe:
        - air
        - air
        - air

        - dragon_head
        - compass
        - dragon_head

        - air
        - air
        - air

  distance_travelled:
    display: "&bDistance Travelled: %value%"
    applicable-to:
      - boots
    tracker:
      item: compass
      name: "&eTracker - Distance Travelled"
      lore:
        - "&8Drop this onto an item with /stattrackers"
        - "&8to display the distance you've travelled"
      craftable: true
      recipe:
        - air
        - paper
        - air

        - paper
        - compass
        - paper

        - air
        - paper
        - air

  headshots:
    display: "&bHeadshots: %value%"
    applicable-to:
      - bow
      - trident
    tracker:
      item: compass
      name: "&eTracker - Headshots"
      lore:
        - "&8Drop this onto an item with /stattrackers"
        - "&8to display the amount of headshots you've hit"
      craftable: true
      recipe:
        - air
        - bow
        - air

        - bow
        - compass
        - bow

        - air
        - bow
        - air
